name: Semantic Release workflow

on: ["push", "pull_request"]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout npm2rpm
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn
      - name: Run Tests
        run: yarn test
      - name: Lint commit message
        uses: wagoid/commitlint-github-action@v1
        with:
          configFile: .commitlintrc.json
